#!/bin/bash
# inject-skill.sh - Inject Plan Mode Rules as additionalContext at session start

cat << 'EOF'
{
  "hookSpecificOutput": {
    "hookEventName": "SessionStart",
    "additionalContext": "Plan Review Guidelines (plan-guardian plugin):\n\n(1) Plan-reviewer agent (advisory, path A): After writing a plan and before exiting plan mode, you SHOULD consider launching the plan-reviewer subagent (Agent tool, subagent_type: plan-reviewer). Recommended but NOT mandatory — use your judgment. User can manually trigger via /plan-review. The review checklist lives in ./.plan-review/review-status.md (separate from the plan file). NEVER manually add '- [x] Have I reviewed this plan?' — only the plan-reviewer subagent may do so.\n\n(2) Codex review gate (v1.5.0, path B, opt-out): A PreToolUse:ExitPlanMode hook intercepts your ExitPlanMode calls. If the plan carries no valid Codex-review marker, the hook DENIES the call with a permissionDecisionReason telling you to run /plan-guardian:codex-plan-review first. That command loops `codex exec` reviews against the plan (held in conversation context; a fallback copy is stashed at ./.plan-review/yoplan-pending.md), revises it based on reasonable findings, and on convergence (literal NO_CONCERNS from Codex) appends an inline marker line to the plan as its last line: <!-- codex-reviewed:TOKEN -->. Re-call ExitPlanMode with that MARKED plan text verbatim — the hook recomputes TOKEN over the plan body and allows the call. TOKEN is a keyed sha256 of the plan body (content-bound; revising the plan invalidates the marker and re-arms the gate). The key is resolved by the shared helper (v1.5.1): $CODEX_REVIEW_SECRET if set, else a per-machine auto key file at ~/.claude/plan-guardian/secret (created on first use) — so content-binding works by default with no setup; only if no key can be established does TOKEN fall back to a fixed literal.\n\nGate disabled when: CODEX_PLAN_REVIEW=0 in env, or codex CLI not installed, or jq not installed (hook silently allows in all three cases). When the gate fires, do not paraphrase the rejection — read the hook's permissionDecisionReason and follow it exactly.\n\n(3) Plan-mode permission prompts (v1.5.0): the codex loop runs while you are STILL in plan mode, where Bash prompts like default mode. v1.5.0 writes NO files during the loop — the reviewed-proof rides inside the plan text (tool_input.plan), not the filesystem — so there are no Write/Edit prompts (and the upstream flaky-allow-list bug no longer affects the gate). Only two Bash calls remain: `codex exec` and plan-review-helper.sh digest. If the user is annoyed by those allow prompts, tell them to run /plan-guardian:setup once — it adds two scoped Bash allow-rules (codex exec + plan-review-helper.sh). Do NOT suggest moving state into .claude/: it is a Claude Code protected path that prompts even harder. The ./.plan-review/ dir is used only by the hook (a plain hook-process write, ungated) to stash a fallback plan copy."
  }
}
EOF
